// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;  // ← Usa config web para Linux temporariamente
      default:
        throw UnsupportedError('...');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATnwZy_qEWCSO712rvlTlGgASUnKEVGWM',
    appId: '1:1082826789172:web:2e4dbcd060226154369561',
    messagingSenderId: '1082826789172',
    projectId: 'murilo-21h52m',
    authDomain: 'murilo-21h52m.firebaseapp.com',
    storageBucket: 'murilo-21h52m.firebasestorage.app',
    measurementId: 'G-T8HT5H6BVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIdG0tJX8LOs3yvWLO-3wFm5ISsrMerLw',
    appId: '1:1082826789172:android:ec3446a0b183cd75369561',
    messagingSenderId: '1082826789172',
    projectId: 'murilo-21h52m',
    storageBucket: 'murilo-21h52m.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6m-I119BP5igFSDnV-9EXtx7UTid98PA',
    appId: '1:1082826789172:ios:bb6b698fb8e31e6e369561',
    messagingSenderId: '1082826789172',
    projectId: 'murilo-21h52m',
    storageBucket: 'murilo-21h52m.firebasestorage.app',
    iosBundleId: 'com.example.lego',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6m-I119BP5igFSDnV-9EXtx7UTid98PA',
    appId: '1:1082826789172:ios:bb6b698fb8e31e6e369561',
    messagingSenderId: '1082826789172',
    projectId: 'murilo-21h52m',
    storageBucket: 'murilo-21h52m.firebasestorage.app',
    iosBundleId: 'com.example.lego',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATnwZy_qEWCSO712rvlTlGgASUnKEVGWM',
    appId: '1:1082826789172:web:26bada18bdf591ca369561',
    messagingSenderId: '1082826789172',
    projectId: 'murilo-21h52m',
    authDomain: 'murilo-21h52m.firebaseapp.com',
    storageBucket: 'murilo-21h52m.firebasestorage.app',
    measurementId: 'G-QY7MP5Y79J',
  );

}